improved the code with the method
iq100bl/HomeworkRepository pull request #6
Opened 2021-04-08 17:51 UTC by iq100bl

improved the code with the method, and formatted the methods

2021-04-09 18:02 UTC, rubleuskia requested changes
Improve more, check this example
```c#
  case "thu" or "thursday":
      Console.ForegroundColor = ConsoleColor.Magenta;
      y = DayOfWeek.Thursday;
      Daily(y);
      break;
```

* pass `ConsoleColor.Magenta` as a parameter into `Daily`
* why do you need `y` here?

2021-04-10 08:55 UTC, iq100bl commented on Candelader v2/Candelader v2/Program.cs
> +            static void Daily(DayOfWeek y)
done

2021-04-10 09:03 UTC, iq100bl commented on Candelader v2/Candelader v2/Program.cs
> +                    }
я это не понял. мне вывод записать методом? но все строки разные, и получиться что на каждую строку вывода выйдет один метод.

2021-04-10 12:57 UTC, iq100bl commented on Candelader v2/Candelader v2/Program.cs
> +                    }
вывод о выходных будет менее логичен " untlill weekend: 4 day(s), today weekend- false" , или "untill weekend: 0 day(s), today weekend- true" одно вытекает из другого. моё решение более громаздко, но выдаёт более логичный результат. ну или я не понял что ты имел ввиду

2021-04-10 12:57 UTC, merged